<template>
  <div>
    <div class="loadingio-spinner-dual-ring-y1f2vcdnfzb"><div class="ldio-b073b5dxyqi">
    <div></div><div><div></div></div>
    </div></div>
</div>
</template>

<script>
export default {
  name: 'Spinner',
}
</script>

<style scoped>

@keyframes ldio-b073b5dxyqi {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-b073b5dxyqi div { box-sizing: border-box!important }
.ldio-b073b5dxyqi > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #ff006b transparent #ff006b transparent;
  animation: ldio-b073b5dxyqi 0.83003300330033003s linear infinite;
}
.ldio-b073b5dxyqi > div:nth-child(2) { border-color: transparent }
.ldio-b073b5dxyqi > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-b073b5dxyqi > div:nth-child(2) div:before, .ldio-b073b5dxyqi > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #ff006b;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #ff006b;
}
.ldio-b073b5dxyqi > div:nth-child(2) div:after { 
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #ff006b;
}
.loadingio-spinner-dual-ring-y1f2vcdnfzb {
  width: 66px;
  height: 66px;
  display: inline-block;
  overflow: hidden; 
  background: none;
  position: absolute;
  margin: auto;
}
.ldio-b073b5dxyqi {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.66);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-b073b5dxyqi div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
